#include<stdio.h>
#include<string.h>
int main()
{
    char input[102],output[210],count;
	int len,i,j,k;
	fflush(stdin);
	while(gets(input)!=NULL)
	{
		len=strlen(input);
		if(len==0)
			strcpy(output,"\0");
		else if(len==1)
		{
			if(input[0]=='1')
				strcpy(output,"1111\0");
			else
			{
				j=0;
				output[j++]='1';
				output[j++]=input[0];
				output[j++]='1';
				output[j]='\0';
			}
		}
		else
		{
            i=0;
			j=0;
			k=1;
			count='0';
			for(i=0,k=1;k<len;)
			{
				if(input[i]==input[k])
				{
					while(input[i]==input[k]&&k<len&&count<'9')
					{
						count++;
						i++;
						k++;
					}
					
					if(count<'9')
                        count++;
					output[j++]=count;
	                output[j++]=input[i];
					count='0';
					if(k<(len-1))
					{
					    k++;
					    i++;
                    }
                    if(k==(len-1))
                    {
                        if(input[len-1]==input[len-2])
                        {
                            output[j++]='2';
                            output[j++]=input[len-1];
                        }
                        else
                        {
                            output[j++]='1';
                            if(input[len-2]=='1')
                            {
                                output[j++]='1';
                                output[j++]='1';
                            }
                            else
                                output[j++]=input[len-2];
                            if(input[len-1]=='1')
                            {
                                output[j++]='1';
                                output[j++]='1';
                            }
                            else
                                output[j++]=input[len-1];
                            output[j++]='1';
                        }
                        k++;
                    }
                }
                else
                {
                    output[j++]='1';
                    while(input[i]!=input[k]&&k<len)
                    {
                        if(input[i]=='1')
                        {
                            output[j++]='1';
                            output[j++]='1';
                            i++;
                            k++;
                        }
                        else
                        {   
							output[j++]=input[i];
                            i++;
                            k++;
                        }
                    }
                    if(k==(len-1))
                    {
                        if(input[len-1]==input[len-2])
                        {
                            output[j++]='2';
                            output[j++]=input[len-1];
                        }
                        else
                        {
                            output[j++]='1';
                            if(input[len-2]=='1')
                            {
                                output[j++]='1';
                                output[j++]='1';
                            }
                            else
                                output[j++]=input[len-2];
                            if(input[len-1]=='1')
                            {
                                output[j++]='1';
                                output[j++]='1';
                            }
                            else
                                output[j++]=input[len-1];
                            output[j++]='1';
                        }
                        k++;
                    }
                    else if(input[i]==input[k])
                        output[j++]='1';
                }
			}
			output[j]='\0';
		}
		puts(output);
        fflush(stdin);
    }
    return 0;
}   
